kind: pipeline
type: docker
name: build

platform:
  arch: amd64
  os: linux

trigger:
  event:
  - push
  - pull_request

steps:
- name: build-backend
  image: golang:1.23
  volumes:
  - name: deps
    path: /go
  commands:
  - go get ./...
  - go build cmd/wallet/main.go

- name: test-backend
  image: golang:1.23
  volumes:
  - name: deps
    path: /go
  commands:
  - go test ./...

volumes:
- name: deps
  temp: {}

---
kind: pipeline
type: docker
name: release-linux-amd64

platform:
  arch: amd64
  os: linux

trigger:
  event:
  - tag

steps:
- name: build-frontend
  image: flarexio/angular:19
  commands:
  - cd app
  - npm install
  - ng build

- name: build-backend
  image: golang:1.23-alpine
  commands:
  - apk add git gcc musl-dev
  - go build -o release/linux/amd64/wallet cmd/wallet/main.go

- name: publish-frontend
  image: plugins/docker
  settings:
    dockerfile: build/Dockerfile.frontend.linux.amd64
    repo: flarexio/wallet-app
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: REGISTRY_USERNAME
    password: 
      from_secret: REGISTRY_PASSWORD

- name: publish-backend
  image: plugins/docker
  settings:
    dockerfile: build/Dockerfile.backend.linux.amd64
    repo: flarexio/wallet
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: REGISTRY_USERNAME
    password: 
      from_secret: REGISTRY_PASSWORD

---
kind: pipeline
type: docker
name: release-manifest

platform:
  arch: amd64
  os: linux

trigger:
  event:
  - tag

steps:
- name: publish-frontend
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: build/manifest.frontend.txt
    username:
      from_secret: REGISTRY_USERNAME
    password: 
      from_secret: REGISTRY_PASSWORD

- name: publish-backend
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: build/manifest.backend.txt
    username:
      from_secret: REGISTRY_USERNAME
    password: 
      from_secret: REGISTRY_PASSWORD

depends_on:
  - release-linux-amd64
