keys:
  google:
    projectID: flarex-439501
    location: global
    keyRing: wallet
    key: main

persistence:
  driver: composite
  composite:
    main:
      driver: solana
      solana:
        rpc: https://api.devnet.solana.com
        program: fx72MZ7SPxwePzFiMagFZakeXxaJn7oLGDd3wxLuENL
        path: # default: $HOME/.flarex/wallet
        account: id.json
    cache:
      driver: badger
      badger:
        name: wallets
        path: # default: $HOME/.flarex/wallet
        # inmem: false

identity:
  baseURL: identity.flarex.io
  jwt:
    secret: jwt_secret_key
    audiences:
    - wallet.flarex.io
